version: '2'

services:
  drupal: 
    image: drupal
    ports: 
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupa-themes:/var/www/html/themes
  postgres:
    image: postgres
    environment:
      - POSTGRESPASSWORD=mypassword
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: