# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.thechain.tech:
    container_name: orderer.thechain.tech
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/thechain.tech/orderers/orderer.thechain.tech/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/thechain.tech/orderers/orderer.thechain.tech/tls/:/var/hyperledger/orderer/tls
    - orderer.thechain.tech:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.alexander.thechain.tech:
    container_name: peer0.alexander.thechain.tech
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.alexander.thechain.tech
      - CORE_PEER_ADDRESS=peer0.alexander.thechain.tech:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.alexander.thechain.tech:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.alexander.thechain.tech:7051
      - CORE_PEER_LOCALMSPID=AlexanderMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/alexander.thechain.tech/peers/peer0.alexander.thechain.tech/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/alexander.thechain.tech/peers/peer0.alexander.thechain.tech/tls:/etc/hyperledger/fabric/tls
        - peer0.alexander.thechain.tech:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.alexander.thechain.tech:
    container_name: peer1.alexander.thechain.tech
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.alexander.thechain.tech
      - CORE_PEER_ADDRESS=peer1.alexander.thechain.tech:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.alexander.thechain.tech:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.alexander.thechain.tech:7051
      - CORE_PEER_LOCALMSPID=AlexanderMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/alexander.thechain.tech/peers/peer1.alexander.thechain.tech/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/alexander.thechain.tech/peers/peer1.alexander.thechain.tech/tls:/etc/hyperledger/fabric/tls
        - peer1.alexander.thechain.tech:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.jesus.thechain.tech:
    container_name: peer0.jesus.thechain.tech
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.jesus.thechain.tech
      - CORE_PEER_ADDRESS=peer0.jesus.thechain.tech:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.jesus.thechain.tech:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.jesus.thechain.tech:7051
      - CORE_PEER_LOCALMSPID=JesusMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/jesus.thechain.tech/peers/peer0.jesus.thechain.tech/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/jesus.thechain.tech/peers/peer0.jesus.thechain.tech/tls:/etc/hyperledger/fabric/tls
        - peer0.jesus.thechain.tech:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.jesus.thechain.tech:
    container_name: peer1.jesus.thechain.tech
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.jesus.thechain.tech
      - CORE_PEER_ADDRESS=peer1.jesus.thechain.tech:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.jesus.thechain.tech:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.jesus.thechain.tech:7051
      - CORE_PEER_LOCALMSPID=JesusMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config//peerOrganizations/jesus.thechain.tech/peers/peer1.jesus.thechain.tech/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config//peerOrganizations/jesus.thechain.tech/peers/peer1.jesus.thechain.tech/tls:/etc/hyperledger/fabric/tls
        - peer1.jesus.thechain.tech:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
