NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.alexander.thechain.tech-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.alexander.thechain.tech-cert.pem
    OrganizationalUnitIdentifier: peer
