NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.jesus.thechain.tech-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.jesus.thechain.tech-cert.pem
    OrganizationalUnitIdentifier: peer
